# Generated by Django 3.1.2 on 2020-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('cancelled', 'cancelled'), ('dispatched', 'dispatched')], default='ordered', max_length=100),
        ),
    ]
